services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - main

  backend:
    build: .
    environment:
      DJANGO_SECRET_KEY:
      DJANGO_DEBUG:
      POSTGRES_NAME:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_HOST:
      POSTGRES_PORT:
    command: >
      sh -c "
        python manage.py makemigrations scanlate &&
        python manage.py migrate &&
        python manage.py loaddata init_data.json &&     
        python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    networks:
      - main

volumes:
  pgdata:

networks:
  main:
    driver: bridge